# Generated by Django 3.2.12 on 2022-02-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_i_am_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
