# Generated by Django 3.2.12 on 2022-03-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hello_i_am_app', '0002_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
